[package]
name = "gof-rust"
version = "0.1.0"
authors = ["Jakub Miernik <jakub1miernik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgref = ""
rand = ""
